name = "Noahs-Server"
author = "Noah"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2b8e97bb6f7eab40dcaaf3ea131a66a867ce63f29c88fb805a78fa91484b5f4"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
