name = "Noahs-Server"
author = "Noah"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73192379c459bcd1b37f2774de41c7fce676f537f41d6ba541aa7f6dcfe12477"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
