name = "Noahs-Server"
author = "Noah"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a171f9285feb97807085f8a0f82a013dfaf6b648538f24aac5d9615127a115fc"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
